const app=document.getElementById('app');
const title=document.getElementById('pageTitle');
const toast=document.getElementById('toast');
const STORAGE='cw_research_lab_state_v4';
const defaults={
  roadmapDone:{},roadmapNotes:{},green:{},yellow:{},blue:{},table:Array.from({length:6},()=>({ref:'',objective:'',approach:'',methodology:'',findings:'',limitations:''})),
  images:{problem:'',architecture:'',flow:'',diagram:''},results:[],references:[],workspace:{notes:'',facts:'',decisions:'',questions:'',sourcePlan:'',protocol:'',evidence:'',future:'',gap:''}
};
function loadState(){try{const x=JSON.parse(localStorage.getItem(STORAGE)||'{}');return {...defaults,...x,roadmapDone:{...defaults.roadmapDone,...(x.roadmapDone||{})},roadmapNotes:{...defaults.roadmapNotes,...(x.roadmapNotes||{})},green:{...defaults.green,...(x.green||{})},yellow:{...defaults.yellow,...(x.yellow||{})},blue:{...defaults.blue,...(x.blue||{})},images:{...defaults.images,...(x.images||{})},workspace:{...defaults.workspace,...(x.workspace||{})},table:Array.isArray(x.table)&&x.table.length?x.table:defaults.table,results:Array.isArray(x.results)?x.results:[],references:Array.isArray(x.references)?x.references:[]}}catch{return JSON.parse(JSON.stringify(defaults))}}
const state=loadState();
function save(msg='Saved locally'){localStorage.setItem(STORAGE,JSON.stringify(state));showToast(msg)}
function showToast(x){toast.textContent=x;toast.classList.add('show');clearTimeout(showToast.t);showToast.t=setTimeout(()=>toast.classList.remove('show'),1800)}
function esc(s=''){return String(s).replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]))}
const pages={overview:'Project Overview',papers:'Research Papers',roadmap:'Research Roadmap',green:'Green',yellow:'Yellow',blue:'Blue'};
function nav(page){document.querySelectorAll('.nav').forEach(x=>x.classList.toggle('active',x.dataset.page===page));title.textContent=pages[page];render(page);window.scrollTo({top:0,behavior:'smooth'});closeMobileSidebar()}
document.querySelectorAll('.nav').forEach(x=>x.onclick=()=>nav(x.dataset.page));
function toggleSidebar(){document.body.classList.toggle('sidebar-collapsed');localStorage.setItem('cw_sidebar_collapsed',document.body.classList.contains('sidebar-collapsed'))}
function closeMobileSidebar(){document.getElementById('sidebar').classList.remove('open')}
document.getElementById('menu').onclick=()=>document.getElementById('sidebar').classList.toggle('open');
document.getElementById('brandToggle').onclick=toggleSidebar;
if(localStorage.getItem('cw_sidebar_collapsed')==='true')document.body.classList.add('sidebar-collapsed');
// Hidden workspace remains reachable only from inside this project; the shortcut is intentionally not shown in normal navigation.
document.addEventListener('keydown',e=>{if(e.ctrlKey&&e.shiftKey&&e.key.toLowerCase()==='c'){e.preventDefault();location.href='private.html'}});

const researchQuestion='Considering opinions of local citizens, Indians, international audiences, experts, officials and governing bodies, what are the major perceived benefits and risks of hosting the 2030 Commonwealth Games in Ahmedabad, and what patterns emerge from the collected evidence?';
const pipeline=['Review / Opinion Collection','Storage','Apache Spark / PySpark','Cleaning / Normalization','Exact Duplicate Removal','Semantic Representation','Opinion Clustering','Representative Opinion + Prevalence','Location / Stakeholder Metadata','Aspect Extraction','Sentiment Analysis','Contextual Relevance / Weight','Opinion Graph','Graph-Based Ranking','Redundancy-Aware Summary','Stakeholder / Location / Aspect Results'];

function renderOverview(){app.innerHTML=`
<section class="card hero">
  <div class="hero-copy"><span class="pill">RESEARCH PROJECT</span><h2>Big Data-Based Text Summarization and Sentiment Analysis of Commonwealth Games Reviews</h2><p>Big Data-based analysis of large-scale opinions and evidence about Ahmedabad hosting the 2030 Commonwealth Games, combining sentiment, aspects, semantic opinion grouping, contextual relevance and graph-based summarization.</p><div class="hero-actions"><button class="primary" onclick="nav('roadmap')">Open Research Roadmap →</button><button class="secondary" onclick="nav('papers')">Read research papers</button></div></div>
  <div class="hero-stat"><span>Research stages</span><strong>22</strong><small>research workflow</small></div>
</section>
<div class="grid three"><div class="stat card"><b>GREEN</b><span>Proposal, motivation, related work, gap and architecture.</span></div><div class="stat card"><b>YELLOW</b><span>Actual implementation, dataset, results, discussion and conclusion.</span></div><div class="stat card"><b>BLUE</b><span>Final abstract, problem, objective, methodology and findings.</span></div></div>
<div class="grid two"><article class="card"><div class="card-title"><span>Research question</span><span class="tag">CORE</span></div><p>${esc(researchQuestion)}</p></article><article class="card"><div class="card-title"><span>Purpose</span><span class="tag">WHY</span></div><p>Analyze how different stakeholder groups perceive the benefits, risks and major aspects of Ahmedabad hosting the 2030 Commonwealth Games, while reducing semantic redundancy so repeated paraphrases do not dominate the evidence.</p></article></div>
<article class="card"><div class="card-title"><span>Why this topic was chosen</span><span class="tag">SELECTION</span></div><div class="selection-grid"><div><b>Big Data relevance</b><p>Large-scale public, media and institutional text creates a realistic text-analytics problem.</p></div><div><b>Real-world application</b><p>The analysis can organize diverse reactions around Ahmedabad 2030 into evidence-backed summaries.</p></div><div><b>Opinion redundancy</b><p>Many people may express the same underlying view using different wording.</p></div><div><b>Stakeholder context</b><p>Local, national, international, expert and official perspectives may have different relevance.</p></div><div><b>Research potential</b><p>The project combines established methods into a transparent, reproducible domain-specific pipeline.</p></div><div><b>Viva-friendly</b><p>The pipeline can be explained from collection through preprocessing, sentiment, graph ranking and summary generation.</p></div></div></article>
<article class="card"><div class="card-title"><span>Keywords & topics covered</span><span class="tag">RESEARCH</span></div><div class="chips"><span>Big Data Analytics</span><span>Text Summarization</span><span>Sentiment Analysis</span><span>Natural Language Processing</span><span>Opinion Mining</span><span>Key Point Analysis</span><span>Aspect-Based Sentiment</span><span>Semantic Clustering</span><span>Opinion Prevalence</span><span>Graph Ranking</span><span>Ahmedabad 2030</span><span>Commonwealth Games</span></div></article>
<article class="card"><div class="card-title"><span>Technical parameters</span><span class="tag">PROJECT SETUP</span></div><div class="selection-grid"><div><b>Processing</b><p>Python + Apache Spark / PySpark</p></div><div><b>Semantic representation</b><p>Sentence embeddings and similarity</p></div><div><b>Analysis</b><p>Aspect extraction + sentiment analysis</p></div><div><b>Graph methods</b><p>Sentence/opinion similarity graph + ranking</p></div><div><b>Storage</b><p>CSV / JSON pilot and final datasets</p></div><div><b>Evaluation</b><p>F1, clustering checks, ROUGE and redundancy analysis</p></div></div></article>
<div class="grid two"><article class="card"><div class="card-title"><span>Proposed output</span></div><ol class="clean-list"><li>Curated multi-source opinion/evidence dataset.</li><li>Exact and semantic redundancy handling with prevalence.</li><li>Stakeholder, location, source and event-stage metadata.</li><li>Aspect and sentiment analysis.</li><li>Contextual relevance/authority weighting.</li><li>Graph-based, non-redundant summaries.</li><li>Evaluation results and an IEEE-style research paper.</li></ol></article><article class="card"><div class="card-title"><span>Core research flow</span></div><div class="pipeline">${pipeline.map((x,i)=>`<div>${i+1}.<br><b>${esc(x)}</b></div>${i<pipeline.length-1?'<i>→</i>':''}`).join('')}</div></article></div>`}

const roadmap=[
['01','Freeze Research Question and Scope','Freeze the exact question, population, event boundary, objectives, contribution and what the system will not claim.','Research scope brief','GREEN'],
['02','Literature Review','Read the selected papers and record objective, approach, methodology, findings, limitations and direct relevance.','Literature matrix','GREEN'],
['03','Literature Comparison and Research Gap','Compare existing summarization, KPA, ABSA, redundancy and graph approaches and state the specific gap.','Research gap statement','GREEN'],
['04','Source and Data Collection Plan','Define public, media, official, expert and independent sources, collection methods and source priorities.','Source plan','GREEN'],
['05','Research Protocol','Freeze inclusion/exclusion criteria, schema, event stages, metadata, labeling rules and evaluation subsets.','Research protocol','GREEN'],
['06','Pilot Dataset','Collect a small diverse pilot and inspect language, source mix, duplicates, relevance and metadata availability.','Pilot dataset','YELLOW'],
['07','Data Understanding and Labeling','Manually inspect and label a pilot subset for sentiment, aspect, stakeholder, location and semantic redundancy.','Gold/pilot labels','YELLOW'],
['08','Semantic Opinion Redundancy Design','Define exact duplicate removal, semantic grouping, representative selection and prevalence retention.','Redundancy protocol','GREEN'],
['09','Stakeholder / Location Classification','Design transparent rules for Ahmedabad, India, international, official, expert, media and public categories.','Metadata classification scheme','GREEN'],
['10','Aspect and Sentiment Design','Define the aspect taxonomy and sentiment labels; document ambiguity handling and validation.','Aspect/sentiment protocol','GREEN'],
['11','Contextual Weighting Design','Define topic-dependent relevance and authority criteria; plan sensitivity analysis instead of arbitrary universal weights.','Weighting model','GREEN'],
['12','Green Submission','Complete the Green proposal with verified background, motivation, literature, gap, contribution and architecture.','GREEN submission','GREEN'],
['13','Final Data Collection','Automate scalable collection through permitted APIs/public sources while preserving provenance and collection dates.','Raw final dataset','YELLOW'],
['14','Data Preprocessing','Clean, normalize, language-handle, filter spam/irrelevance and remove exact duplicates.','Processed dataset','YELLOW'],
['15','Opinion Clustering and Representative Selection','Create semantic clusters, choose representative opinions and retain cluster prevalence.','Opinion clusters','YELLOW'],
['16','Sentiment and Aspect Analysis','Run the selected sentiment and aspect methods and validate on manually labeled data.','Aspect/sentiment outputs','YELLOW'],
['17','Graph-Based Summarization','Build similarity graphs, rank salient opinions/sentences and apply redundancy-aware selection.','Summary outputs','YELLOW'],
['18','Evaluation','Evaluate sentiment, clustering, redundancy, summarization and contextual weighting using actual experiments.','Metrics and figures','YELLOW'],
['19','Interpretation and Discussion','Explain stakeholder differences, dominant aspects, contradictions, limitations and failure cases without overstating conclusions.','Discussion evidence','YELLOW'],
['20','Yellow Submission','Complete technology, equations, pseudocode, dataset, execution flow, results, discussion and conclusion from actual work.','YELLOW submission','YELLOW'],
['21','Final Conclusion','Freeze the actual conclusions and derive the final methodology from the completed implementation.','Final conclusion','BLUE'],
['22','Blue Submission','Complete the abstract, problem formation, objective, methodology and findings using the finished research.','BLUE submission','BLUE']
];
function renderRoadmap(){const done=Object.values(state.roadmapDone).filter(Boolean).length;const pct=Math.round(done/roadmap.length*100);app.innerHTML=`<div class="card roadmap-hero"><span class="pill">22-STAGE RESEARCH ROADMAP</span><h2>Research Roadmap</h2><p class="muted">This is a research-stage workflow, not a day-by-day schedule. Open a stage to see exactly what to do, what to find, what to enter and where the result will be used.</p><div class="progress"><div class="progress-track"><i style="width:${pct}%"></i></div><span>${done} / ${roadmap.length} stages completed</span></div></div><div class="roadmap">${roadmap.map(s=>{const d=!!state.roadmapDone[s[0]];return `<article class="stage ${s[4].toLowerCase()} ${d?'completed':''}" onclick="openRoadmapStage('${s[0]}')"><div class="stage-top"><div class="stage-number">${s[0]}</div><div><div class="mini">${s[4]}</div><h4>${esc(s[1])}</h4></div><span class="stage-status">${d?'✓ DONE':'OPEN →'}</span></div><p>${esc(s[2])}</p><div class="task"><strong>Output: ${esc(s[3])}</strong><small>Open for task instructions, editable notes and status.</small></div></article>`}).join('')}</div>`}
function openRoadmapStage(id){const s=roadmap.find(x=>x[0]===id);if(!s)return;const use=s[4]==='GREEN'?['Green → Introduction','Green → Related Work','Green → Proposed Research Work']:s[4]==='YELLOW'?['Yellow → Implementation and Execution flow','Yellow → Results','Yellow → Discussion']:['Blue → Methodology','Blue → Findings','Blue → Abstract'];const modal=document.createElement('div');modal.className='modal';modal.innerHTML=`<div class="modal-box roadmap-modal"><div class="modal-head"><strong>Stage ${s[0]} · ${esc(s[1])}</strong><button class="modal-close" onclick="this.closest('.modal').remove()">×</button></div><div class="modal-body"><span class="pill ${s[4].toLowerCase()}">${s[4]}</span><h2>${esc(s[1])}</h2><div class="road-detail-grid"><div><b>What I have to do</b><p>${esc(s[2])}</p></div><div><b>What I need to find</b><p>Record the concrete evidence, sources, decisions, measurements or observations required to complete this stage.</p></div><div><b>What I should enter</b><p>Save your notes, links, evidence, decisions, questions and completed outputs in the field below.</p></div><div><b>Where it will be used</b><p>${use.map(esc).join('<br>')}</p></div></div><label class="check-row"><input type="checkbox" id="roadDone" ${state.roadmapDone[id]?'checked':''}> Mark this stage completed</label><label class="field"><span>Notes / Evidence</span><textarea id="roadNote" placeholder="Record what you researched, what you found, decisions, links, evidence or problems..."></textarea></label><div class="modal-actions"><button class="secondary" onclick="this.closest('.modal').remove()">Cancel</button><button class="primary" onclick="saveRoadmapStage('${id}',this)">Save Stage</button></div></div></div>`;document.body.appendChild(modal);document.getElementById('roadNote').value=state.roadmapNotes[id]||''}
function saveRoadmapStage(id,btn){state.roadmapDone[id]=document.getElementById('roadDone').checked;state.roadmapNotes[id]=document.getElementById('roadNote').value;save('Roadmap stage saved');btn.closest('.modal').remove();renderRoadmap()}

function renderPapers(){const q=state.paperQuery||'';app.innerHTML=`<div class="card"><span class="pill">LITERATURE REVIEW</span><h2>30 Research Papers</h2><p class="muted">The collection keeps the supplied graph-based paper and adds three directly relevant opinion-summarization papers. Open any paper for reading, notes and a 15-minute reading tracker.</p><input id="paperSearch" class="search" value="${esc(q)}" placeholder="Search title, method or relevance..."><div id="paperList" class="paper-list"></div></div>`;const list=document.getElementById('paperList');const search=document.getElementById('paperSearch');function draw(){state.paperQuery=search.value;const term=search.value.toLowerCase();list.innerHTML=papers.filter(p=>(p.title+p.about+p.use).toLowerCase().includes(term)).map(p=>`<article class="card paper paper-link" onclick="location.href='paper.html?id=${p.id}'"><div class="paper-number">${String(p.id).padStart(2,'0')}</div><div><div class="year">PAPER ${p.id} · ${p.year}</div><h4>${esc(p.title)}</h4><p>${esc(p.about)}</p><div class="mini"><b>Use in this project:</b> ${esc(p.use)}</div></div><div class="paper-actions"><a class="btn" href="paper.html?id=${p.id}" onclick="event.stopPropagation()">Open Paper →</a></div></article>`).join('')||'<div class="empty">No matching paper.</div>'}search.oninput=draw;draw()}

const greenSections=[
['g-intro','1. Introduction','section',[
 ['g-problem','a. Problem formation with background information','What is the problem, its background, scope and context?'],
 ['g-motivation','b. Motivation - Facts - Need Analysis(Statistics)','Enter verified facts, statistics and need analysis. Cite sources.'],
 ['g-diagram','i. Overall problem depicts by a diagram','Upload a diagram that visually depicts the overall problem.'],
 ['g-prior','ii. Work done by other researcher for problem and the analytical technique','Summarize what researchers have done and the analytical techniques used.'],
 ['g-contribution','c. Contribution - your novel work','State the precise contribution of this research.']]],
['g-related','2. Related Work','section',[
 ['g-related-a','a. Work done by different researcher in the same problem area','Summarize the related work and group it by technique/theme.'],
 ['g-related-b','b. A comparative study with table(5 to 10 research papers)','Use the editable six-row comparison table below.']]],
['g-proposed','3. Proposed Research Work','section',[
 ['g-pdef','a. Problem definition','Write the final problem definition.'],
 ['g-solution','b. Proposed solution','Describe the proposed solution.'],
 ['g-architecture','c. Proposed system architecture','Upload the proposed architecture diagram and explain it below.'],
 ['g-components','d. Explanation of each component of architecture','Explain every architecture component and its role.']]]
];
function fieldBlock(id,label,placeholder,group='green'){const val=(state[group]&&state[group][id])||'';return `<div class="editable-block"><button class="collapse-head" onclick="toggleBlock(this)"><span>${esc(label)}</span><b>⌄</b></button><div class="collapse-body"><textarea data-group="${group}" data-key="${id}" placeholder="${esc(placeholder)}">${esc(val)}</textarea></div></div>`}
function renderGreen(){app.innerHTML=`<div class="card submission-intro"><span class="pill">GREEN PART</span><h2>Action/ Application</h2><p class="muted">Action/ Application is a heading, not an editable box. The sections below are your proposal workspace.</p></div>${greenSections.map(s=>`<section class="hier-section"><button class="major-head" onclick="toggleBlock(this)"><span>${esc(s[1])}</span><b>⌄</b></button><div class="major-body">${s[3].map(x=>x[0]==='g-diagram'?diagramBlock('problem',x[1]):x[0]==='g-architecture'?diagramBlock('architecture',x[1])+fieldBlock('g-architecture-note','Architecture explanation','Explain the architecture shown in the diagram.','green'):x[0]==='g-related-b'?fieldBlock(x[0],x[1],x[2],'green')+literatureTableHTML():fieldBlock(x[0],x[1],x[2],'green')).join('')}</div></section>`).join('')}`;bindGreenAutosave()}
function literatureTableHTML(){return `<div class="table-wrap"><table class="research-table"><thead><tr><th>Ref.</th><th>Objective</th><th>Approach</th><th>Methodology</th><th>Findings</th><th>Limitations</th></tr></thead><tbody>${state.table.map((r,i)=>`<tr>${['ref','objective','approach','methodology','findings','limitations'].map(k=>`<td><textarea data-row="${i}" data-col="${k}">${esc(r[k]||'')}</textarea></td>`).join('')}</tr>`).join('')}</tbody></table></div><button class="secondary small-btn" onclick="saveLiteratureTable()">Save Table</button>`}
function diagramBlock(key,label){const img=state.images[key];return `<div class="editable-block"><button class="collapse-head" onclick="toggleBlock(this)"><span>${esc(label)}</span><b>⌄</b></button><div class="collapse-body"><div class="upload-box"><input type="file" accept="image/*" id="upload-${key}" onchange="uploadImage('${key}',this)"><label for="upload-${key}" class="upload-label">Upload Image</label>${img?`<div class="image-preview"><img src="${img}" alt="Uploaded diagram"><button class="secondary small-btn" onclick="removeImage('${key}')">Remove Image</button></div>`:'<p class="muted">Your uploaded image will appear inside this section and persist in this browser.</p>'}</div></div></div>`}
function bindGreenAutosave(){document.querySelectorAll('[data-group=green]').forEach(x=>x.oninput=()=>{state.green[x.dataset.key]=x.value;localStorage.setItem(STORAGE,JSON.stringify(state))});document.querySelectorAll('[data-row]').forEach(x=>x.oninput=()=>{state.table[Number(x.dataset.row)][x.dataset.col]=x.value;localStorage.setItem(STORAGE,JSON.stringify(state))})}
function saveLiteratureTable(){document.querySelectorAll('[data-row]').forEach(x=>{state.table[Number(x.dataset.row)][x.dataset.col]=x.value});save('Literature table saved')}
function uploadImage(key,input){const file=input.files?.[0];if(!file)return;const reader=new FileReader();reader.onload=()=>{state.images[key]=reader.result;save('Image saved in this browser');renderGreen()};reader.readAsDataURL(file)}
function removeImage(key){state.images[key]='';save('Image removed');renderGreen()}

const yellowStructure=[['y-method','4. Methodology and Concepts',[['y-tech','a. Technology and concept applied to achieve proposed research work','Record the actual technologies and concepts used.'],['y-math','b. Mathematical equations and derivations','Enter final equations and derivations used in the implemented system.'],['y-algo','c. Pseudocode(Flow Chart) / algorithm for proposed execution flow','Enter the final algorithm after implementation.']]],['y-exec','5. Implementation and Execution flow',[['y-dataset','a. Dataset selection','Record actual sources, collection dates, counts and provenance.'],['y-pre','b. Data preprocessing if required','Record actual cleaning, normalization, filtering and deduplication.'],['y-char','c. CHaracteristics and behavior of selected dataset','Enter actual counts, distributions, languages, sources and observed behavior.'],['y-env','d. Execution environment (software and hardware)','Record hardware, OS, Python/Spark versions, libraries and runtime.'],['y-flow','e. Execution flow explanation','Explain what actually happened during execution, including failures and corrections.']]],['y-results','6. Results',[['y-results-text','Results workspace','Only enter measured results. Do not invent metrics.']]],['y-discussion','7. Discussion',[['y-discussion-text','Discussion workspace','Interpret actual results, compare with literature and explain limitations.']]],['y-conclusion','8. Conclusion',[['y-conclusion-text','Conclusion workspace','Write only after actual research is complete.']]]];
function renderYellow(){app.innerHTML=`<div class="card submission-intro"><span class="pill">YELLOW PART</span><h2>4. Methodology and Concepts</h2><p class="muted">This workspace records actual implementation and evidence. Replace placeholders only after the corresponding research or experiment has been completed.</p></div>${yellowStructure.map(s=>`<section class="hier-section"><button class="major-head" onclick="toggleBlock(this)"><span>${esc(s[1])}</span><b>⌄</b></button><div class="major-body">${s[2].map(x=>x[0]==='y-algo'?fieldBlock(x[0],x[1],x[2],'yellow')+diagramBlock('flow','Flow Chart / Algorithm Diagram'):fieldBlock(x[0],x[1],x[2],'yellow')).join('')}${s[0]==='y-results'?resultsHTML():''}</div></section>`).join('')}<section class="hier-section"><button class="major-head" onclick="toggleBlock(this)"><span>References</span><b>⌄</b></button><div class="major-body">${referencesHTML()}</div></section>`;bindYellowAutosave()}
function bindYellowAutosave(){document.querySelectorAll('[data-group=yellow]').forEach(x=>x.oninput=()=>{state.yellow[x.dataset.key]=x.value;localStorage.setItem(STORAGE,JSON.stringify(state))})}
function resultsHTML(){return `<div class="results-area"><div class="results-head"><b>Result blocks</b><button class="secondary small-btn" onclick="addResult()">+ Add Result</button></div>${state.results.map((r,i)=>`<article class="result-block"><input data-result="${i}:title" value="${esc(r.title||'')}" placeholder="Result title"><textarea data-result="${i}:description" placeholder="Description">${esc(r.description||'')}</textarea>${r.image?`<img src="${r.image}" alt="Result graph"><button class="secondary small-btn" onclick="removeResultImage(${i})">Remove Image</button>`:''}<input type="file" accept="image/*" onchange="uploadResultImage(${i},this)"><textarea data-result="${i}:observation" placeholder="Observation">${esc(r.observation||'')}</textarea><button class="secondary small-btn danger" onclick="deleteResult(${i})">Delete Result</button></article>`).join('')}</div>`}
function addResult(){state.results.push({title:'',description:'',image:'',observation:''});save('Result block added');renderYellow()}
function deleteResult(i){state.results.splice(i,1);save('Result deleted');renderYellow()}
function uploadResultImage(i,input){const f=input.files?.[0];if(!f)return;const r=new FileReader();r.onload=()=>{state.results[i].image=r.result;save('Result image saved');renderYellow()};r.readAsDataURL(f)}
function removeResultImage(i){state.results[i].image='';save('Result image removed');renderYellow()}
document.addEventListener('input',e=>{const el=e.target;if(!el.dataset.result)return;const [i,k]=el.dataset.result.split(':');state.results[Number(i)][k]=el.value;localStorage.setItem(STORAGE,JSON.stringify(state))});
function referencesHTML(){return `<div class="references-area"><div class="results-head"><b>References</b><button class="secondary small-btn" onclick="addReference()">+ Add Reference</button></div>${state.references.map((r,i)=>`<div class="reference-row"><input data-ref="${i}" value="${esc(r)}" placeholder="IEEE-style reference"><button class="secondary small-btn danger" onclick="deleteReference(${i})">Delete</button></div>`).join('')}</div>`}
function addReference(){state.references.push('');save('Reference added');renderYellow()}
function deleteReference(i){state.references.splice(i,1);save('Reference deleted');renderYellow()}
document.addEventListener('input',e=>{if(e.target.dataset.ref!==undefined){state.references[Number(e.target.dataset.ref)]=e.target.value;localStorage.setItem(STORAGE,JSON.stringify(state))}});

const blueFields=[['abstract','Abstract(200 - 250 - 300 Words)(Who is the benefactor of the project)','Write the final abstract after the completed research.'],['problem','Problem Formation(1 - 2 Lines)','Final concise problem statement.'],['objective','Objective(2 - 3 Lines)','Final objective.'],['method','Methodology(Get from the conclusion)','Derive methodology from the completed implementation and conclusion.'],['findings','Findings(What we will do at the end)','Only actual findings supported by completed research.']];
function renderBlue(){app.innerHTML=`<div class="card submission-intro"><span class="pill">BLUE PART</span><h2>Final Research Summary</h2><p class="muted">Complete this section last. It is the compact final version of the completed research.</p></div>${blueFields.map(x=>fieldBlock('b-'+x[0],x[1],x[2],'blue')).join('')}`;document.querySelectorAll('[data-group=blue]').forEach(t=>t.oninput=()=>{state.blue[t.dataset.key]=t.value;localStorage.setItem(STORAGE,JSON.stringify(state))})}

function toggleBlock(btn){const body=btn.nextElementSibling;if(!body)return;const open=!body.classList.contains('hidden');body.classList.toggle('hidden',open);const b=btn.querySelector('b');if(b)b.textContent=open?'⌄':'⌃'}

function render(page){({overview:renderOverview,roadmap:renderRoadmap,papers:renderPapers,green:renderGreen,yellow:renderYellow,blue:renderBlue}[page]||renderOverview)()}
render('overview');
