const app = document.getElementById('app');
const title = document.getElementById('pageTitle');
const toast = document.getElementById('toast');
const STORAGE = 'cw_research_lab_state_v3';

const defaults = {
  notes:'', facts:'', decisions:'', questions:'', sourcePlan:'', protocol:'',
  roadmapDone:{}, roadmapNotes:{}, literature:{},
  gAction:'',gProblem:'',gMotivation:'',gPrior:'',gContribution:'',gPdef:'',gSolution:'',gArchitecture:'',gComponents:'',gRelatedWork:'',
  yTech:'',yMath:'',yAlgo:'',yDataset:'',yPre:'',yChar:'',yEnv:'',yFlow:'',yResults:'',yDiscussion:'',yConclusion:'',yDiagram:'',
  bAbstract:'',bProblem:'',bObjective:'',bMethod:'',bFindings:'',bTitle:'',bKeywords:''
};
function loadState(){try{return {...defaults,...JSON.parse(localStorage.getItem(STORAGE)||'{}')}}catch{return {...defaults}}}
const state = loadState();
function save(){localStorage.setItem(STORAGE,JSON.stringify(state));showToast('Saved locally');}
function showToast(x){toast.textContent=x;toast.classList.add('show');clearTimeout(showToast.t);showToast.t=setTimeout(()=>toast.classList.remove('show'),1800)}
function esc(s=''){return String(s).replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]))}
const pages={overview:'Project Overview',roadmap:'Research Roadmap',papers:'Research Papers',workspace:'Research Workspace',green:'GREEN — Proposal',yellow:'YELLOW — Research',blue:'BLUE — Final'};
function nav(page){document.querySelectorAll('.nav').forEach(x=>x.classList.toggle('active',x.dataset.page===page));title.textContent=pages[page];if(page==='workspace'){location.href='private.html';return}render(page);window.scrollTo({top:0,behavior:'smooth'});closeMobileSidebar()}
document.querySelectorAll('.nav').forEach(x=>x.onclick=()=>nav(x.dataset.page));
function toggleSidebar(){document.body.classList.toggle('sidebar-collapsed');localStorage.setItem('cw_sidebar_collapsed',document.body.classList.contains('sidebar-collapsed'));}
function closeMobileSidebar(){document.getElementById('sidebar').classList.remove('open')}
document.getElementById('menu').onclick=()=>document.getElementById('sidebar').classList.toggle('open');
document.getElementById('sidebarToggle').onclick=toggleSidebar;
if(localStorage.getItem('cw_sidebar_collapsed')==='true')document.body.classList.add('sidebar-collapsed');
// Hidden area is intentionally registered only inside the Commonwealth project, never on RL home.
document.addEventListener('keydown',e=>{if(e.ctrlKey&&e.shiftKey&&e.key.toLowerCase()==='c'){e.preventDefault();location.href='private.html'}});

function renderOverview(){app.innerHTML=`
<div class="card hero"><span class="pill">RESEARCH PROJECT 02</span><h2>Big Data-Based Text Summarization and Sentiment Analysis of Commonwealth Games Reviews</h2><p>Research Lab is a structured environment for planning, executing and documenting this research. The public interface contains the roadmap, literature and proposal/research/final sections; the detailed research workspace remains hidden and is opened only with <b>Ctrl + Shift + C</b>.</p><div class="hero-actions"><button class="primary" onclick="nav('roadmap')">Open Research Roadmap →</button><button class="secondary" onclick="nav('papers')">Open Research Papers →</button></div></div>
<div class="grid three"><div class="stat card"><b>GREEN</b><span>Proposal, gap, contribution and architecture.</span></div><div class="stat card"><b>YELLOW</b><span>Actual implementation, evidence, results and discussion.</span></div><div class="stat card"><b>BLUE</b><span>Final paper-ready summary after research is complete.</span></div></div>
<div class="section-title"><h3>Research question</h3></div><div class="card"><p>Considering opinions of local citizens, Indians, international audiences, experts, officials and governing bodies, what are the major perceived benefits and risks of hosting the 2030 Commonwealth Games in Ahmedabad, and what patterns emerge from the collected evidence?</p><div class="notice"><b>Research boundary:</b> the system analyzes collected evidence and reported perceptions; it does not predetermine the final result.</div></div>
<div class="section-title"><h3>Research pipeline</h3></div><div class="card pipeline"><div class="pipe">Collect<b>Opinions + evidence</b></div><div class="arrow">→</div><div class="pipe">Clean<b>Normalize + filter</b></div><div class="arrow">→</div><div class="pipe">Group<b>Semantic opinions</b></div><div class="arrow">→</div><div class="pipe">Analyze<b>Aspect + sentiment</b></div><div class="arrow">→</div><div class="pipe">Context<b>Stakeholder + source</b></div><div class="arrow">→</div><div class="pipe">Rank<b>Graph + relevance</b></div><div class="arrow">→</div><div class="pipe">Summarize<b>Non-redundant output</b></div></div>`}

const roadmap=[
['01','Freeze research scope','Write the exact research question, boundaries, objective and contribution.','Research brief','GREEN'],
['02','Build the literature matrix','Read the core papers and record objective, approach, methodology, findings, limitations and relevance.','Literature matrix','GREEN'],
['03','Identify the research gap','Compare existing methods with the CWG-specific system and state the precise gap.','Research gap statement','GREEN'],
['04','Design the source plan','Define public opinion, media, official, expert and independent sources plus inclusion rules.','Source plan','GREEN'],
['05','Design the pilot protocol','Define the pilot size, schema, labels, event stages and evaluation subsets.','Research protocol','GREEN'],
['06','Freeze the architecture','Document collection → cleaning → semantic grouping → sentiment → weighting → graph → summary.','Architecture diagram','GREEN'],
['07','Complete GREEN proposal','Turn the verified planning material into the proposal without inventing results.','GREEN draft','GREEN'],
['08','Collect pilot evidence','Gather a small, diverse pilot and record provenance, date, source and context.','Pilot dataset','YELLOW'],
['09','Validate duplicate handling','Test exact duplicate removal and semantic grouping while preserving cluster prevalence.','Cluster decisions','YELLOW'],
['10','Finalize collection pipeline','After the pilot, automate scalable collection using permitted sources/APIs and maintain provenance.','Raw dataset','YELLOW'],
['11','Run NLP preprocessing','Clean, normalize and classify source, location, stakeholder and language metadata.','Processed dataset','YELLOW'],
['12','Run aspect + sentiment analysis','Extract major aspects and sentiment from the collected evidence.','Aspect/sentiment outputs','YELLOW'],
['13','Apply contextual weighting','Define topic-dependent relevance/authority weighting and document sensitivity checks.','Weighting results','YELLOW'],
['14','Build graph summarization','Construct the opinion/sentence graph, rank candidates and reduce redundancy.','Summary outputs','YELLOW'],
['15','Evaluate the system','Measure clustering, sentiment, redundancy, summarization and weighting effects using actual data.','Metrics + figures','YELLOW'],
['16','Analyze failure cases','Document errors, ambiguous evidence, source bias, language issues and unexpected behavior.','Failure-case log','YELLOW'],
['17','Complete YELLOW','Fill implementation, equations, algorithm, dataset, execution, results, discussion and conclusion from actual work.','YELLOW draft','YELLOW'],
['18','Write BLUE methodology','Derive the final methodology from the completed implementation and conclusion.','Methodology section','BLUE'],
['19','Write BLUE findings','Write only findings supported by completed experiments and evidence.','Findings section','BLUE'],
['20','Finalize research package','Complete abstract, keywords, references, figures, limitations, reproducibility notes and final review.','Final research package','BLUE']
];
function renderRoadmap(){app.innerHTML=`<div class="card roadmap-hero"><span class="pill">20-STAGE RESEARCH ROADMAP</span><h2>Research Roadmap</h2><p class="muted">Every stage is clickable. Open a stage to see its exact work, mark it complete and save your own notes. Progress is stored in this browser.</p><div class="progress"><div class="progress-track"><i id="roadProgress"></i></div><span id="roadProgressText"></span></div></div><div class="roadmap">${roadmap.map((s,i)=>{const done=!!state.roadmapDone[s[0]];return `<article class="stage ${s[4].toLowerCase()} ${done?'completed':''}" onclick="openRoadmapStage('${s[0]}')" tabindex="0" onkeydown="if(event.key==='Enter'||event.key===' '){openRoadmapStage('${s[0]}')}"><div class="stage-top"><div class="stage-number">${s[0]}</div><div><div class="mini">${s[4]}</div><h4>${esc(s[1])}</h4></div><span class="stage-status">${done?'✓ DONE':'OPEN →'}</span></div><p>${esc(s[2])}</p><div class="task"><strong>Output: ${esc(s[3])}</strong><small>Click to open stage details and your editable notes.</small></div></article>`}).join('')}</div>`;updateRoadProgress()}
function updateRoadProgress(){const done=Object.values(state.roadmapDone).filter(Boolean).length;const pct=Math.round(done/20*100);const b=document.getElementById('roadProgress');if(b)b.style.width=pct+'%';const t=document.getElementById('roadProgressText');if(t)t.textContent=`${done} / 20 stages completed`}
function openRoadmapStage(id){const s=roadmap.find(x=>x[0]===id);if(!s)return;const modal=document.createElement('div');modal.className='modal';modal.id='roadModal';modal.innerHTML=`<div class="modal-box roadmap-modal"><div class="modal-head"><strong>Stage ${s[0]} · ${esc(s[1])}</strong><button class="modal-close" onclick="closeRoadmapStage()">×</button></div><div class="modal-body"><span class="pill ${s[4].toLowerCase()}">${s[4]}</span><h2>${esc(s[1])}</h2><p>${esc(s[2])}</p><div class="detail-box"><b>Expected output</b><span>${esc(s[3])}</span></div><label class="check-row"><input type="checkbox" id="roadDone" ${state.roadmapDone[id]?'checked':''}> Mark this stage completed</label><label class="field"><span>My notes for this stage</span><textarea id="roadNote" placeholder="Record what you researched, decisions, links, questions or evidence..."></textarea></label><div class="modal-actions"><button class="secondary" onclick="closeRoadmapStage()">Cancel</button><button class="primary" onclick="saveRoadmapStage('${id}')">Save Stage</button></div></div></div>`;document.body.appendChild(modal);document.getElementById('roadNote').value=state.roadmapNotes[id]||'';}
function closeRoadmapStage(){document.getElementById('roadModal')?.remove()}
function saveRoadmapStage(id){state.roadmapDone[id]=document.getElementById('roadDone').checked;state.roadmapNotes[id]=document.getElementById('roadNote').value;save();closeRoadmapStage();renderRoadmap()}

function renderPapers(){app.innerHTML=`<div class="card"><span class="pill">LITERATURE</span><h2>Research Papers</h2><p class="muted">Open any paper as a dedicated research page. Notes are stored per paper.</p><input id="paperSearch" class="search" placeholder="Search papers, methods or relevance..."/><div id="paperList" class="paper-list"></div></div>`;const list=document.getElementById('paperList'),search=document.getElementById('paperSearch');function draw(){const q=search.value.toLowerCase();list.innerHTML=papers.filter(p=>(p.title+p.about+p.use).toLowerCase().includes(q)).map(p=>`<article class="card paper paper-link" role="link" tabindex="0" onclick="location.href='paper.html?id=${p.id}'" onkeydown="if(event.key==='Enter'||event.key===' '){location.href='paper.html?id=${p.id}'}"><div class="paper-number">${String(p.id).padStart(2,'0')}</div><div><div class="year">PAPER ${p.id} · ${p.year}</div><h4>${esc(p.title)}</h4><p class="muted">${esc(p.about)}</p><div class="mini"><b>Use in this project:</b> ${esc(p.use)}</div></div><div class="paper-actions"><a class="btn" href="paper.html?id=${p.id}" onclick="event.stopPropagation()">Open Paper →</a></div></article>`).join('')||'<div class="empty">No matching paper.</div>'}search.oninput=draw;draw()}

const greenFields=[['g-action','Action / Application','What real-world action or application will this research support?'],['g-problem','Problem formation','What is the problem, context and scope?'],['g-motivation','Motivation — facts — need analysis','Enter verified statistics, facts and evidence. Cite every claim.'],['g-prior','Previous researchers and analytical techniques','Summarize relevant papers and techniques with citations.'],['g-contribution','Your contribution','State exactly what your system adds beyond existing work.'],['g-pdef','Final problem definition','Write the final problem definition.'],['g-solution','Proposed solution','Describe the proposed solution.'],['gArchitecture','Architecture / flow','Edit the architecture or flow here. You are not locked to the initial proposal.'],['g-components','Component explanations','Explain each architecture component and why it exists.'],['gRelatedWork','Related-work notes','Add or edit your related-work notes and references.']];
function fieldsHTML(fields,statePrefix=''){return fields.map(([id,label,ph])=>{const key=id;return `<div class="card editable-card"><h3>${esc(label)}</h3><textarea id="${id}" placeholder="${esc(ph)}">${esc(state[key]||'')}</textarea></div>`}).join('')}
function renderGreen(){app.innerHTML=`<div class="card"><span class="pill">SUBMISSION 1</span><h2>GREEN — Proposal Workspace</h2><p class="muted">Everything below is editable. Change the initial material whenever your research direction changes. Save at any time; your work is stored locally.</p></div><div class="grid two">${fieldsHTML(greenFields)}</div><div class="card"><h3>Research Architecture Diagram Text</h3><textarea id="gDiagram" placeholder="Edit the architecture text shown in the proposal..."></textarea></div><div class="save-bar"><span>Green notes are stored in your browser.</span><button class="primary" onclick="saveGreen()">Save GREEN</button></div>`;document.getElementById('gDiagram').value=state.gDiagram||'Collection → Storage → Cleaning → Exact Deduplication → Semantic Similarity → Opinion Clustering → Representative Opinion + Prevalence → Metadata Classification → Aspect + Sentiment → Contextual Weighting → Opinion/Sentence Graph → Graph Ranking → Redundancy Control → Stakeholder / Location / Aspect Summaries';}
function saveGreen(){const ids=greenFields.map(x=>x[0]).concat(['gDiagram']);ids.forEach(id=>{state[id]=document.getElementById(id).value});save()}

const yellowFields=[['yTech','Technology and concepts applied','Actual technologies, libraries and concepts used.'],['yMath','Mathematical equations and derivations','Record final equations and derivations.'],['yAlgo','Pseudocode / algorithm','Write the final algorithm after implementation.'],['yDataset','Dataset selection','Actual sources, dates, counts, licensing and collection method.'],['yPre','Data preprocessing','Actual cleaning and normalization steps.'],['yChar','Dataset characteristics and behavior','Actual counts, language, source distribution, sentiment/aspect distributions, duplicates, missing metadata.'],['yEnv','Execution environment','Hardware, OS, Python/Spark versions, libraries, runtime.'],['yFlow','Execution flow explanation','Explain what actually happened, including failures and corrections.'],['yResults','Results','Only measured results. Add links/names of CSVs, figures and tables.'],['yDiscussion','Discussion','Interpret results, compare with literature, explain unexpected findings and limitations.'],['yConclusion','Conclusion','What did the completed research demonstrate?'],['yDiagram','Implementation flow / diagram text','Edit the implementation flow whenever the actual system changes.']];
function renderYellow(){app.innerHTML=`<div class="card"><span class="pill">SUBMISSION 2</span><h2>YELLOW — Implementation & Results Workspace</h2><p class="muted">All content is editable and saved locally. Replace the starter text with the actual implementation evidence when available.</p></div><div class="grid two">${fieldsHTML(yellowFields)}</div><div class="save-bar"><span>Never overwrite measured results with predictions.</span><button class="primary" onclick="saveYellow()">Save YELLOW</button></div>`;for(const [id] of yellowFields)document.getElementById(id).value=state[id]||''}
function saveYellow(){yellowFields.forEach(([id])=>state[id]=document.getElementById(id).value);save()}

const blueFields=[['bTitle','Final title','Final research title.'],['bAbstract','Abstract','Final abstract after the research is complete.'],['bProblem','Problem Formation','Final concise problem statement.'],['bObjective','Objective','Final objective.'],['bMethod','Methodology','Derive this from the completed research, not the original proposal.'],['bFindings','Findings','Actual final findings after research.'],['bKeywords','Keywords','Final keywords for the paper.']];
function renderBlue(){app.innerHTML=`<div class="card"><span class="pill">FINAL SUMMARY</span><h2>BLUE — Final Research Summary</h2><p class="muted">This section is fully editable. Write it after the research is completed and save your changes.</p></div><div class="grid two">${fieldsHTML(blueFields)}</div><div class="save-bar"><span>Blue is the final editable summary.</span><button class="primary" onclick="saveBlue()">Save BLUE</button></div>`}
function saveBlue(){blueFields.forEach(([id])=>state[id]=document.getElementById(id).value);save()}

function render(page){({overview:renderOverview,roadmap:renderRoadmap,papers:renderPapers,green:renderGreen,yellow:renderYellow,blue:renderBlue}[page]||renderOverview)()}
render('overview');
